### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by arska** [denis-sokolov/remove-github-forks#121]
Hello @denis-sokolov 

I created a Dockerfile (https://github.com/arska/remove-github-forks) and Docker image build (https://hub.docker.com/r/arska/remove-github-forks) to run remove-github-forks for myself.

Do you see a broader need for this to include it in this project, so should I prepare a pullrequest or not?

Cheers,
Aarno

**Comment by denis-sokolov** [comment]
Hey, thanks for bringing this to my attention. I’d love to mention it in the readme and allow the readme for the docker image to explain more. Please check #122 and see if I got it right. And thanks!
