### ISSUE TITLE
Allow interactive use

### ISSUE THREAD

**Issue by waldyrious** [denis-sokolov/remove-github-forks#13]
I don't want to delete all my forks. It'd be great to have an option to approve each repo for deletion individually. An interface similar to `git add -p` would be great: y(es), n(o), a(ll), n(one).

**Comment by denis-sokolov** [comment]
Thank you for your suggestion. I am not sure about your workflow. Do you know that `remove-github-forks` will not delete any fork that has any branch that is not yet upstream? If you keep a fork for your personal reference, without committing to it, you can add a single commit on a single branch and this will prevent it from being deleted.

It is my opinion that it in the end will be more efficient even for you - `remove-github-forks` will be idempotent for you and you can run it automatically, if you want.

That said, if you really see value in an interactive mode, it should be very simple to add such functionality to the library, a PR is welcome. [In `bin.js` we now confirm all repos at once.](https://github.com/denis-sokolov/remove-github-forks/blob/master/bin.js#L48) This would need to be modified to confirm in a loop.

**Comment by waldyrious** [comment]
Fair enough. There are a few forks I want to maintain for safekeeping (in case the original author deletes their repo), and I would prefer not to pollute the history with commits even if not in the main branch. But that's a reasonable workaround, I'll consider it. Thanks for the detailed response!
