### ISSUE TITLE
"No useless repositories found."

### ISSUE THREAD

**Issue by waldyrious** [denis-sokolov/remove-github-forks#28]
I'm getting the message shown in the title, but I have [plenty of eligible forks](https://github.com/waldyrious?tab=repositories). Any hints on how to debug this?

**Comment by denis-sokolov** [comment]
Hm. This is interesting. I assume you don't use `--user` option. It could be a mistake in logic, in which case you can add a few `console.log`s to see what [goes wrong](https://github.com/denis-sokolov/remove-github-forks/blob/f4914529fd1e797c49f1eab76c8c92cf5d1700d7/src/index.js#L33-L52
).

We also have two limitations: no support for pagination (#1, so you might happen to have a 100 useful repositories) and rate limiting (#7, so some requests might be failing, although I would expect them to fail loudly).

**Comment by waldyrious** [comment]
>  I assume you don't use `--user` option.

Indeed I didn't use it, but I just tried it and the result was the same. In fact, I `console.log`ged the `repos` and the `forks` variables, and the result is the same regardless of whether I use the `--user` option. There indeed seems to be an error, since `forks` contained repos owned by organizations I belong to.

> you might happen to have a 100 useful repositories

This is also a likely case. I have been sending dozens of PRs similar to #23, and many of those are still pending. If that's the case, would it be possible to change the logic so that the relevant error is presented?

**Comment by denis-sokolov** [comment]
I see. So, apparently `--user` [filters repositories after the fact](https://github.com/denis-sokolov/remove-github-forks/blob/d1eb7d4b1926dc104121bfea807bfa5eff28ccf3/src/bin.js#L38-L40), so its behavior is not representative of anything. Your problem is then one [of pagination](https://github.com/denis-sokolov/remove-github-forks/blob/f4914529fd1e797c49f1eab76c8c92cf5d1700d7/src/index.js#L36) (#1) :(.

**Comment by waldyrious** [comment]
If you give me a little more detail regarding how pagination should be implemented, I can give it a shot :)

**Comment by denis-sokolov** [comment]
@waldyrious, I have done some research and [posted it](https://github.com/denis-sokolov/remove-github-forks/issues/1#issuecomment-233289041) on the relevant issue.
