### ISSUE TITLE
Worth sorting the token?

### ISSUE THREAD

**Issue by hemanth** [denis-sokolov/remove-github-forks#4]
After `remove-github-forks <token>`it would be good to save it into `~/.rmgf` for future refs.

**Comment by denis-sokolov** [comment]
I have added a suggestion to README how you can easily achieve this without custom storage method.
Please let me know if you have any questions or suggestions yet!

**Comment by hemanth** [comment]
`alias` ftw I agree, but would it be even more useful if we could create that alias the source the rc file programatically ?

**Comment by denis-sokolov** [comment]
I don't see much use in that. Especially when you can even copy and paste the example alias, don't even need to know how aliases work.

**Comment by hemanth** [comment]
heh heh :+1:
