### ISSUE TITLE
No common ancestor between $COMMIT and master.

### ISSUE THREAD

**Issue by balupton** [denis-sokolov/remove-github-forks#42]
```
$ remove-github-forks a4df6099f47ca53f583baedc358389369f49589a
Inspected 36/63 (chai)
(node:5109) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): {"message":"No common ancestor between cd70c88c6516ad5e04ce17ab7db4b1df2b728b50 and master.","documentation_url":"https://developer.github.com/v3/repos/commits/#compare-two-commits"}
(node:5109) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{"message":"Server Error: Sorry, this diff is taking too long to generate.","errors":[{"resource":"Comparison","field":"diff","code":"not_available"}],"documentation_url":"https://developer.github.com/v3/repos/commits/#compare-two-commits"}
```

**Comment by denis-sokolov** [comment]
@balupton, you should [revoke the token](https://github.com/settings/tokens) you have pasted here, it provides some access to your account.

The error was temporary, and there is not much value in trying to resolve it. Instead, in version 1.4.0 we know skip over repositories that triggered errors and continue with the rest of them. The user is then welcome to try to delete the problematic repositories manually, or just rerun remove-github-forks later.

Thanks for the report that triggered the new feature!

**Comment by balupton** [comment]
> @balupton, you should revoke the token you have pasted here, it provides some access to your account.

Whoops!

**Comment by balupton** [comment]
> The error was temporary, and there is not much value in trying to resolve it. Instead, in version 1.4.0 we now skip over repositories that triggered errors and continue with the rest of them. The user is then welcome to try to delete the problematic repositories manually, or just rerun remove-github-forks later.
> 
> Thanks for the report that triggered the new feature!

Cool, thanks for the fix!
