### ISSUE TITLE
Maybe add an FAQ to the readme?

### ISSUE THREAD

**Issue by ntwb** [denis-sokolov/remove-github-forks#44]
Here's a couple of questions I'd like to see answered in a FAQ:

Q. Does this detect and account for branches in the user fork that haven't been submitted as PR?
A. ???

Q. Does this prompt you delete all repos in one hit or each repo separately?
A. You will be prompted to delete all of them at once

(I'd like to see the above changed to prompt for each repo as I've a couple of forks I'd like to keep)

**Comment by denis-sokolov** [comment]
Thanks for bringing your feedback. The tool does detect branches that are not open PRs yet. In 5e12e20e4ae42ab I have clarified the readme a bit.

For the second question, I think the [existing demonstration of the usage](https://github.com/denis-sokolov/remove-github-forks#run) is enough. At this stage I believe the better default behavior is to only ask a single question for all forks at once. I would likely accept a pull request that would add an option triggering individual questions to accommodate for your use case. Unfortunately, I have no plans to add such an option myself.

Again, thanks for your feedback and feel free to provide more, even in this topic. But for now I’m closing it as answered.

**Comment by ntwb** [comment]
Thanks 👍
