### ISSUE TITLE
Cookies must be enabled to use GitHub

### ISSUE THREAD

**Issue by StellarDoor5319** [denis-sokolov/remove-github-forks#62]
When I try to delete the repositories, I get the following error:

    Cookies must be enabled to use GitHub.

Why does this happen? How can I fix the problem?

**Comment by denis-sokolov** [comment]
Haven't seen this before. Could you try setting an explicit `host: api.github.com`, as suggested in https://github.com/octokit/rest.js/issues/544#issuecomment-305793473?

**Comment by StellarDoor5319** [comment]
@denis-sokolov This is still happening, even after #63.

**Comment by denis-sokolov** [comment]
We miscommunicated. I thought you tested #63, especially given the language "Fixes #62". =7

Well, let's look for another solution.

**Comment by StellarDoor5319** [comment]
I tried to test but got errors completely unrelated to this (something to do with my local Node installation). As the issue you linked to had comments saying it fixed the problem, I assumed it would work the same here. But obviously, it didn't.
