### ISSUE TITLE
rate limiting required

### ISSUE THREAD

**Issue by khushil** [denis-sokolov/remove-github-forks#7]
When trying to remove a number of repo's:

/usr/local/lib/node_modules/remove-github-forks/shouldDeleteFork.js:32
				throw err;
				      ^
Error: {
  "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",
  "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
}

Probably need to rate limit to stop this happening?

**Comment by denis-sokolov** [comment]
Apparently [GitHub requests](https://developer.github.com/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits) requests for a single user to happen concurrently.

We [can do that](https://github.com/denis-sokolov/remove-github-forks/blob/master/index.js#L65), although obviously it will slightly slow down the work. The will of GitHub, however, is primary, so this should be done.

**Comment by conikeec** [comment]
Any update on this patch. A simple blocking sleep between deletes will help

**Comment by denis-sokolov** [comment]
I am wary of it, actually. Serial checks for all repositories will make the script considerably slower.
GitHub wants it, and it should be implemented, but perhaps we then need a progress bar, seeing how the process will slow down. :(

**Comment by denis-sokolov** [comment]
I am working on this. Soon we will stop being blocked by the abuse detection mechanism.

**Comment by denis-sokolov** [comment]
Fixed in 1.3.0! \o/
