### ISSUE TITLE
Fails when forked repo has been deleted

### ISSUE THREAD

**Issue by corollari** [denis-sokolov/remove-github-forks#91]
Steps to reproduce:
1. User A creates repo
2. User B forks repo
3. User A deletes repo
4. User B runs `remove-github-forks`

**Comment by denis-sokolov** [comment]
Great report, thank you. I think the fix ought to be simple, when we fetch the original repo we should catch a 404 and prematurely return `false` from `shouldDeleteFork`.

https://github.com/denis-sokolov/remove-github-forks/blob/5ecc5610851bb2e32cfa1f5aabbac32f2f36f569/src/shouldDeleteFork.js#L48-L51
